name = "workflow-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

kv_namespaces = [
  { binding = "KV_RATE_LIMIT", id = "YOUR_KV_ID_HERE" }
]
